name: project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^3.1.1

  cupertino_icons: ^1.0.2
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  gallery_saver_plus: ^3.0.1
  flutter_vision: ^1.1.4
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt
    - assets/yolov5s.tflite
  